global:
  scrape_interval:     60s
  evaluation_interval: 60s
 
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['10.10.10.21:9090']
        labels:
          instance: prometheus
                  
  - job_name: alertmanagers
    static_configs:
      - targets: ["10.10.10.21:9093"]
        labels:
          instance: alertmanagers
                  
  - job_name: pushgateway
    static_configs:
      - targets: ['10.10.10.21:9091']
        labels:
          instance: pushgateway
